### ISSUE TITLE
matching between prediction and ground-truth

### ISSUE THREAD

**Issue by s-wang** [art-programmer/PlaneNet#7]
Hi, thanks for your impressive work. 
I have one question about the loss computation. Since the predicted plane is order-less, to compute the loss between prediction and ground-truth, we have to find the matching relationship between them. Based on your code, I find two possible solutions:
1) Find the matching by nn-search, but in my understanding, since the samples in on batch varies a lot, the matching relationship might differ between different samples.
2) Use anchor. I am not sure what the anchor is, could you please provide some explanations about it?
And, could you share what strategy did you use to train the model?  
Thanks again :)

**Comment by art-programmer** [comment]
Thank you for your interests in our work. We use nn-search. To deal with the number difference, we pad empty planes in the ground truth set to make the number of planes the same, find the matching, and then ignore those empty planes when computing the final loss.

**Comment by s-wang** [comment]
@art-programmer Thanks for your answers. I still a little confused about the "sameMatching" option. In my understanding, if we set this option on, we'll use the previous matching relationship, but the images varies a lot in one batch or different batches, how do you guarantee the consistency between different images. e.g. in image1, a table plane could be set as 3, but in image2, a table could be set as 7

**Comment by art-programmer** [comment]
Sorry for the confusion. We considered deep supervision (like the stacked hourglass architecture) to make multiple sets of predictions (which share the same target) for each input example. The sameMatching option indicates using the same matching for all of them. Since they share the same target, it makes sense for them to share the same matching. But we found deep supervision doesn't help much. So we didn't use deep supervision and the option is also not used (pred_index always equals to 0).
